#pragma config(Sensor, S1,     X_GYRO,         sensorEV3_Gyro)
#pragma config(Sensor, S2,     Y_GYRO,         sensorEV3_Gyro)
#pragma config(Sensor, S3,     TOUCH_SENSOR,   sensorEV3_Touch)
#pragma config(Sensor, S4,     COLOR_SENSOR,   sensorEV3_Color)
#pragma config(Motor,  motorA,          X_AXIS,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Y_AXIS,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          DRAW_MOTOR,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int DRAW_MOTOR_LIMIT = 145; // The limit above which the drawing head is considered to be "drawing"
const int ACTUATE_SPEED = 20; //The speed at which the drawing head will actuate

void actuate (int sign, bool control) //sign should be -1 or +1

{
    int priorButtonState = SensorValue[TOUCH_SENSOR]; //buttonState = 0 as this function is called only when button has been released

    while ((nMotorEncoder[DRAW_MOTOR]<DRAW_MOTOR_LIMIT && sign > 0) || (nMotorEncoder[DRAW_MOTOR]>10 && sign < 0))//move based on actuation stage
    {

    motor[DRAW_MOTOR]=ACTUATE_SPEED*sign;

    if (control)
    {
     //   joystickControl();

        if (SensorValue[TOUCH_SENSOR]!=1 && priorButtonState==1)
            sign=-sign;

    }

    priorButtonState=SensorValue[TOUCH_SENSOR];
    wait1Msec(10);
    }


    motor[DRAW_MOTOR]=0;


}

void checkActuate (bool & headStateUp, int & priorButtonState)
{

	if(SensorValue[TOUCH_SENSOR] != 1 && priorButtonState==1)
	{
		if(headStateUp)
		{
			actuate(1, 1);
			headStateUp=false;
		}
		else
		{
			actuate(-1, 1);
			headStateUp = true;

		}
	}
	priorButtonState=SensorValue[TOUCH_SENSOR];
	wait1Msec(10);
}
