#pragma config(Sensor, S1,     X_GYRO,         sensorEV3_Gyro)
#pragma config(Sensor, S2,     Y_GYRO,         sensorEV3_Gyro)
#pragma config(Sensor, S3,     DRAW_BUTTON,    sensorEV3_Touch)
#pragma config(Sensor, S4,     COLOR,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          X_AXIS,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Y_AXIS,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          DRAW_MOTOR,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drawing.c" // Shapw drawing functions
#include "movement.c" // Movement funcitons

// Low-level system reset. This should be accessing sensor and motor data directly
void systemReset();

task main(){    
    // Pointers to the encoder values of the x and y axis, used to shorten code and make it more readable
    int* x = &nMotorEncoder[X_AXIS];
    int* y = &nMotorEncoder[Y_AXIS];

    // Records the value of the motor encoder associated with the drawing utensil actuation motor
    int* z = &nMotorEncoder[DRAW_MOTOR];
    
    // The limit on the actuation motor above which the head is considered to be drawing
    const int DRAW_MOTOR_LIMIT = 180;
    const int X_LIMIT = 360*5;
    const int Y_LIMIT = 360*5;

    systemReset();
}
